Repository laminas/laminas-hydrator, pull requests merged in 2020-10, with the labels that each got.

#27 Update map-naming-strategy.md
  docs/book/v3/naming-strategy/map-naming-strategy.md
Labels: Documentation

#23 Fixed StrategyInterface::hydrate() docblock because it is not optional
  src/Strategy/StrategyInterface.php
Labels: Bug, Documentation

#33 Adds Psalm integration
  .travis.yml
  composer.json
  psalm-baseline.xml
  psalm.xml.dist
Labels: Enhancement

#35 Improve code base per Psalm suggestions
  phpcs.xml
  src/StandaloneHydratorPluginManager.php
  test/Aggregate/AggregateHydratorFunctionalTest.php
  test/Aggregate/AggregateHydratorTest.php
  test/Aggregate/ExtractEventTest.php
  test/Aggregate/HydrateEventTest.php
  test/Aggregate/HydratorListenerTest.php
  test/ArraySerializableHydratorTest.php
  test/ArraySerializableTest.php
  test/ClassMethodsTest.php
  test/DelegatingHydratorFactoryTest.php
  test/DelegatingHydratorTest.php
  test/Filter/FilterCompositeTest.php
  test/Filter/MethodMatchFilterTest.php
  test/Filter/NumberOfParameterFilterTest.php
  test/Filter/OptionalParametersFilterTest.php
  test/HydratorAwareTraitTest.php
  test/HydratorClosureStrategyTest.php
  test/HydratorObjectPropertyTest.php
  test/HydratorPluginManagerCompatibilityTest.php
  test/HydratorPluginManagerFactoryTest.php
  test/HydratorStrategyTest.php
  test/HydratorTest.php
  test/HydratorTestTrait.php
  test/Iterator/HydratingArrayIteratorTest.php
  test/Iterator/HydratingIteratorIteratorTest.php
  test/NamingStrategy/CompositeNamingStrategyTest.php
  test/NamingStrategy/IdentityNamingStrategyTest.php
  test/NamingStrategy/MapNamingStrategyTest.php
  test/NamingStrategy/UnderscoreNamingStrategy/CamelCaseToUnderscoreFilterTest.php
  test/NamingStrategy/UnderscoreNamingStrategy/UnderscoreToCamelCaseFilterTest.php
  test/NamingStrategy/UnderscoreNamingStrategyTest.php
  test/ObjectPropertyTest.php
  test/ReflectionTest.php
  test/StandaloneHydratorPluginManagerFactoryTest.php
  test/StandaloneHydratorPluginManagerTest.php
  test/Strategy/BooleanStrategyTest.php
  test/Strategy/CollectionStrategyTest.php
  test/Strategy/DateTimeFormatterStrategyTest.php
  test/Strategy/ExplodeStrategyTest.php
  test/Strategy/HydratorStrategyTest.php
  test/Strategy/SerializableStrategyTest.php
  test/Strategy/StrategyChainTest.php
  test/TestAsset/AggregateObject.php
  test/TestAsset/ClassMethodsCamelCase.php
  test/TestAsset/ClassMethodsCamelCaseMissing.php
  test/TestAsset/ClassMethodsFilterProviderInterface.php
  test/TestAsset/ClassMethodsInvalidParameter.php
  test/TestAsset/ClassMethodsOptionalParameters.php
  test/TestAsset/ClassMethodsProtectedSetter.php
  test/TestAsset/ClassMethodsTitleCase.php
  test/TestAsset/ClassMethodsUnderscore.php
  test/TestAsset/HydratorStrategyEntityA.php
  test/TestAsset/HydratorStrategyEntityB.php
Labels: Enhancement
