Repository laminas/laminas-hydrator, pull requests merged in 2021-06, with the labels that each got.

#52 Fix class method hydrator redundant filter
  src/ClassMethodsHydrator.php
Labels: Bug

#54 Add ScalarTypeStrategy
  composer.json
  composer.lock
  docs/book/naming-strategy/composite-naming-strategy.md
  docs/book/naming-strategy/identity-naming-strategy.md
  docs/book/naming-strategy/map-naming-strategy.md
  docs/book/naming-strategy/underscore-naming-strategy.md
  docs/book/v3/quick-start.md
  docs/book/v4/quick-start.md
  docs/book/v4/strategy.md
  psalm.xml.dist
  src/Strategy/BooleanStrategy.php
  src/Strategy/ScalarTypeStrategy.php
  test/Strategy/ScalarTypeStrategyTest.php
Labels: Enhancement

#56 Correct CompositeNamingStrategy example in docs
  docs/book/v4/naming-strategy/composite-naming-strategy.md
Labels: Documentation

#64 Added `webmozart/assert` dependencies, which was implicitly required through `require-dev`, but not in `require`
  composer.json
  composer.lock
Labels: Bug
